using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SFServer.Services.iAP.Apple
{
    public class AppStoreReceipt
    {
        /// <summary>
        /// See app_item_id.
        /// </summary>
        public string adam_id { get; set; }

        /// <summary>
        /// Generated by App Store Connect and used by the App Store to uniquely identify the app purchased. Apps are assigned this identifier only in production. Treat this value as a 64-bit long integer.
        /// </summary>
        public Int64 app_item_id { get; set; }

        /// <summary>
        /// The app’s version number. The app's version number corresponds to the value of CFBundleVersion (in iOS) or CFBundleShortVersionString (in macOS) in the Info.plist. In production, this value is the current version of the app on the device based on the receipt_creation_date_ms. In the sandbox, the value is always "1.0". 
        /// </summary>
        public string application_version { get; set; }

        /// <summary>
        /// The bundle identifier for the app to which the receipt belongs. You provide this string on App Store Connect. This corresponds to the value of CFBundleIdentifier in the Info.plist file of the app.
        /// </summary>
        public string bundle_id { get; set; }

        /// <summary>
        /// A unique identifier for the app download transaction.
        /// </summary>
        public Int64 download_id { get; set; }

        /// <summary>
        /// The time the receipt expires for apps purchased through the Volume Purchase Program, in a date-time format similar to the ISO 8601.
        /// </summary>
        public string expiration_date { get; set; }

        /// <summary>
        /// The time the receipt expires for apps purchased through the Volume Purchase Program, in UNIX epoch time format, in milliseconds. If this key is not present for apps purchased through the Volume Purchase Program, the receipt does not expire. Use this time format for processing dates.
        /// </summary>
        public string expiration_date_ms { get; set; }

        /// <summary>
        /// The time the receipt expires for apps purchased through the Volume Purchase Program, in the Pacific Time zone. 
        /// </summary>
        public string expiration_date_pst { get; set; }

        /// <summary>
        /// An array that contains the in-app purchase receipt fields for all in-app purchase transactions.
        /// </summary>
        public AppleStoreInAppReceipt[] in_app { get; set; }

        /// <summary>
        /// The version of the app that the user originally purchased. This value does not change, and corresponds to the value of CFBundleVersion (in iOS) or CFBundleShortVersionString (in macOS) in the Info.plist file of the original purchase. In the sandbox environment, the value is always "1.0". 
        /// </summary>
        public string original_application_version { get; set; }

        /// <summary>
        /// The time of the original app purchase, in a date-time format similar to ISO 8601. 
        /// </summary>
        public string original_purchase_date { get; set; }

        /// <summary>
        /// The time of the original app purchase, in UNIX epoch time format, in milliseconds. Use this time format for processing dates.
        /// </summary>
        public string original_purchase_date_ms { get; set; }

        /// <summary>
        /// The time of the original app purchase, in the Pacific Time zone.
        /// </summary>
        public string original_purchase_date_pst { get; set; }

        /// <summary>
        /// The time the user ordered the app available for pre-order, in a date-time format similar to ISO 8601.
        /// </summary>
        public string preorder_date { get; set; }

        /// <summary>
        /// The time the user ordered the app available for pre-order, in UNIX epoch time format, in milliseconds. This field is only present if the user pre-orders the app. Use this time format for processing dates.
        /// </summary>
        public string preorder_date_ms { get; set; }

        /// <summary>
        /// The time the user ordered the app available for pre-order, in the Pacific Time zone.
        /// </summary>
        public string preorder_date_pst { get; set; }

        /// <summary>
        /// The time the App Store generated the receipt, in a date-time format similar to ISO 8601.
        /// </summary>
        public string receipt_creation_date { get; set; }

        /// <summary>
        /// The time the App Store generated the receipt, in UNIX epoch time format, in milliseconds. Use this time format for processing dates. This value does not change.
        /// </summary>
        public string receipt_creation_date_ms { get; set; }

        /// <summary>
        /// The time the App Store generated the receipt, in the Pacific Time zone. 
        /// </summary>
        public string receipt_creation_date_pst { get; set; }

        /// <summary>
        /// The type of receipt generated. The value corresponds to the environment in which the app or VPP purchase was made.
        /// Possible values: Production, ProductionVPP, ProductionSandbox, ProductionVPPSandbox
        /// </summary>
        public string receipt_type { get; set; }

        /// <summary>
        /// The time the request to the verifyReceipt endpoint was processed and the response was generated, in a date-time format similar to ISO 8601.
        /// </summary>
        public string request_date { get; set; }

        /// <summary>
        /// The time the request to the verifyReceipt endpoint was processed and the response was generated, in UNIX epoch time format, in milliseconds. Use this time format for processing dates.
        /// </summary>
        public string request_date_ms { get; set; }

        /// <summary>
        /// The time the request to the verifyReceipt endpoint was processed and the response was generated, in the Pacific Time zone.
        /// </summary>
        public string request_date_pst { get; set; }

        /// <summary>
        /// An arbitrary number that identifies a revision of your app. In the sandbox, this key's value is “0”.
        /// </summary>
        public int version_external_identifier { get; set; }
    }
}
