#!/bin/bash
#
# Prepare the default Icon.plist file generated by Unity
# and prepares it for release
#

projectfile=$1

sed -i '' -e 's/USYM_UPLOAD_AUTH_TOKEN = ""/USYM_UPLOAD_AUTH_TOKEN = "DEAD"/g' "$projectfile"

grep USYM_UPLOAD_AUTH_TOKEN "$projectfile"

exit 0
