// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SFServer.Contexts;

namespace SFServer.Migrations
{
    [DbContext(typeof(PostgreSqlContext))]
    [Migration("20190829234115_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("SFServer.Models.CampaignTime", b =>
                {
                    b.Property<string>("CampaignTimeId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("LevelIndex");

                    b.Property<float>("Time");

                    b.Property<string>("UserId");

                    b.Property<int>("World");

                    b.HasKey("CampaignTimeId");

                    b.ToTable("CampaignTimes");
                });

            modelBuilder.Entity("SFServer.Models.Client", b =>
                {
                    b.Property<string>("ClientId")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Banned");

                    b.HasKey("ClientId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("SFServer.Models.Level", b =>
                {
                    b.Property<string>("LevelId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTimeOffset>("CreatedOn");

                    b.Property<string>("CreatorUserId");

                    b.Property<int>("Deaths");

                    b.Property<int>("Dislikes");

                    b.Property<string>("GameVersion");

                    b.Property<int>("Likes");

                    b.Property<string>("MainColor");

                    b.Property<string>("Name");

                    b.Property<string>("PatternColor");

                    b.Property<int>("Plays");

                    b.Property<float>("Record");

                    b.Property<string>("SerializedLevel");

                    b.Property<string>("SubColor");

                    b.Property<byte[]>("Thumbnail");

                    b.Property<DateTimeOffset>("UpdatedOn");

                    b.Property<string>("UserId");

                    b.Property<string>("WallColor");

                    b.Property<int>("Wins");

                    b.HasKey("LevelId");

                    b.HasIndex("UserId");

                    b.ToTable("Levels");
                });

            modelBuilder.Entity("SFServer.Models.LevelUserStats", b =>
                {
                    b.Property<string>("LevelUserStatsId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("LevelId");

                    b.Property<int>("Opinion");

                    b.Property<string>("UserId");

                    b.Property<float>("bestTime");

                    b.HasKey("LevelUserStatsId");

                    b.HasIndex("UserId");

                    b.ToTable("LevelUserStats");
                });

            modelBuilder.Entity("SFServer.Models.Notifications.Notification", b =>
                {
                    b.Property<string>("NotificationId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Body");

                    b.Property<DateTimeOffset>("CreatedOn");

                    b.Property<int>("NotificationType");

                    b.Property<bool>("Read");

                    b.Property<string>("Title");

                    b.Property<DateTimeOffset>("UpdatedOn");

                    b.Property<string>("UserId");

                    b.HasKey("NotificationId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("SFServer.Models.User", b =>
                {
                    b.Property<string>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTimeOffset?>("AgreedToTermsOfService");

                    b.Property<bool>("Banned");

                    b.Property<DateTimeOffset>("CreatedOn");

                    b.Property<int>("Identifier");

                    b.Property<DateTimeOffset>("LastActive");

                    b.Property<string>("Nickname");

                    b.Property<int>("Role");

                    b.Property<DateTimeOffset>("UpdatedOn");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SFServer.Security.Token", b =>
                {
                    b.Property<string>("TokenId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClientId");

                    b.Property<DateTimeOffset>("CreatedOn");

                    b.Property<string>("TokenString");

                    b.Property<DateTimeOffset>("UpdatedOn");

                    b.Property<string>("UserId");

                    b.HasKey("TokenId");

                    b.HasIndex("UserId");

                    b.ToTable("Tokens");
                });

            modelBuilder.Entity("SFServer.Models.Level", b =>
                {
                    b.HasOne("SFServer.Models.User")
                        .WithMany("Levels")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("SFServer.Models.LevelUserStats", b =>
                {
                    b.HasOne("SFServer.Models.User")
                        .WithMany("LevelStats")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("SFServer.Security.Token", b =>
                {
                    b.HasOne("SFServer.Models.User")
                        .WithMany("Tokens")
                        .HasForeignKey("UserId");
                });
#pragma warning restore 612, 618
        }
    }
}
