// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SFServer.Contexts;

namespace SFServer.Migrations
{
    [DbContext(typeof(PostgreSqlContext))]
    [Migration("20200502000302_modToolsAndTransactionType")]
    partial class modToolsAndTransactionType
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("SFServer.Models.DB.CampaignTime", b =>
                {
                    b.Property<string>("CampaignTimeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LevelIndex")
                        .HasColumnType("integer");

                    b.Property<double>("Time")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<int>("World")
                        .HasColumnType("integer");

                    b.HasKey("CampaignTimeId");

                    b.ToTable("CampaignTimes");
                });

            modelBuilder.Entity("SFServer.Models.DB.Client", b =>
                {
                    b.Property<string>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<bool>("Banned")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FCMToken")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("ClientId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("SFServer.Models.DB.Following", b =>
                {
                    b.Property<string>("FollowingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserBeingFollowedId")
                        .HasColumnType("text");

                    b.Property<string>("UserFollowingId")
                        .HasColumnType("text");

                    b.HasKey("FollowingId");

                    b.HasIndex("UserFollowingId");

                    b.ToTable("Followings");
                });

            modelBuilder.Entity("SFServer.Models.DB.Level", b =>
                {
                    b.Property<string>("LevelId")
                        .HasColumnType("text");

                    b.Property<bool>("Blacklisted")
                        .HasColumnType("boolean");

                    b.Property<int>("CoinsInvested")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatorUserId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("DailyChallengeOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Deaths")
                        .HasColumnType("integer");

                    b.Property<int>("Dislikes")
                        .HasColumnType("integer");

                    b.Property<string>("GameVersion")
                        .HasColumnType("text");

                    b.Property<int>("LifetimeLikes")
                        .HasColumnType("integer");

                    b.Property<int>("Likes")
                        .HasColumnType("integer");

                    b.Property<string>("MainColor")
                        .HasColumnType("text");

                    b.Property<int>("MajorGameVersion")
                        .HasColumnType("integer");

                    b.Property<int>("MinorGameVersion")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("PatternColor")
                        .HasColumnType("text");

                    b.Property<int>("Plays")
                        .HasColumnType("integer");

                    b.Property<double>("Record")
                        .HasColumnType("double precision");

                    b.Property<string>("RecordHolder")
                        .HasColumnType("text");

                    b.Property<string>("SerializedLevel")
                        .HasColumnType("text");

                    b.Property<string>("SubColor")
                        .HasColumnType("text");

                    b.Property<byte[]>("Thumbnail")
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("WallColor")
                        .HasColumnType("text");

                    b.Property<int>("Wins")
                        .HasColumnType("integer");

                    b.HasKey("LevelId");

                    b.HasIndex("UserId");

                    b.ToTable("Levels");
                });

            modelBuilder.Entity("SFServer.Models.DB.LevelOfTheWeek", b =>
                {
                    b.Property<string>("LevelOfTheWeekId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LevelId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("LevelOfTheWeekId");

                    b.ToTable("LevelsOfTheWeek");
                });

            modelBuilder.Entity("SFServer.Models.DB.LevelUserStats", b =>
                {
                    b.Property<string>("LevelUserStatsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("HasGivenLikeBefore")
                        .HasColumnType("boolean");

                    b.Property<string>("LevelId")
                        .HasColumnType("text");

                    b.Property<int>("Opinion")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<double>("bestTime")
                        .HasColumnType("double precision");

                    b.HasKey("LevelUserStatsId");

                    b.ToTable("LevelUserStats");
                });

            modelBuilder.Entity("SFServer.Models.DB.PrivacyPolicyAgreement", b =>
                {
                    b.Property<string>("PrivacyPolicyAgreementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<bool>("Agreed")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("PrivacyPolicyAgreementId");

                    b.ToTable("PrivacyPolicyAgreement");
                });

            modelBuilder.Entity("SFServer.Models.DB.RecentPlay", b =>
                {
                    b.Property<string>("RecentPlayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LevelId")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("RecentPlayId");

                    b.ToTable("RecentPlays");
                });

            modelBuilder.Entity("SFServer.Models.DB.TermsOfServiceAgreement", b =>
                {
                    b.Property<string>("TermsOfServiceAgreementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<bool>("Agreed")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("TermsOfServiceAgreementId");

                    b.ToTable("TermsOfServiceAgreement");
                });

            modelBuilder.Entity("SFServer.Models.DB.Transaction", b =>
                {
                    b.Property<string>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<int>("BalanceAfter")
                        .HasColumnType("integer");

                    b.Property<int>("BalanceBefore")
                        .HasColumnType("integer");

                    b.Property<int>("ChangeInBalance")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("LevelName")
                        .HasColumnType("text");

                    b.Property<bool>("RecivedByPlayer")
                        .HasColumnType("boolean");

                    b.Property<bool>("Refunded")
                        .HasColumnType("boolean");

                    b.Property<int>("TransactionType")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("TransactionId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("SFServer.Models.DB.TrendingLevel", b =>
                {
                    b.Property<string>("TrendingLevelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LevelId")
                        .HasColumnType("text");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.HasKey("TrendingLevelId");

                    b.ToTable("TrendingLevels");
                });

            modelBuilder.Entity("SFServer.Models.DB.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("AgreedToTermsOfService")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Banned")
                        .HasColumnType("boolean");

                    b.Property<int>("Coins")
                        .HasColumnType("integer");

                    b.Property<string>("Color")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FollowerCount")
                        .HasColumnType("integer");

                    b.Property<int>("Identifier")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("LastActive")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LifetimeCoins")
                        .HasColumnType("integer");

                    b.Property<string>("Nickname")
                        .HasColumnType("text");

                    b.Property<bool>("Notification_DailyChallengeResults")
                        .HasColumnType("boolean");

                    b.Property<bool>("Notification_FollowedLikedLevel")
                        .HasColumnType("boolean");

                    b.Property<bool>("Notification_FollowedPlayedLevel")
                        .HasColumnType("boolean");

                    b.Property<bool>("Notification_FollowedPublishedLevel")
                        .HasColumnType("boolean");

                    b.Property<bool>("Notification_MyLevelIsLevelOfTheWeek")
                        .HasColumnType("boolean");

                    b.Property<bool>("Notification_NewDailyChallenge")
                        .HasColumnType("boolean");

                    b.Property<bool>("Notification_NewFollower")
                        .HasColumnType("boolean");

                    b.Property<bool>("Notification_WorldRecordBeaten")
                        .HasColumnType("boolean");

                    b.Property<string>("RestoreToken")
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SFServer.Models.DB.UserCampaignLevelData", b =>
                {
                    b.Property<string>("UserCampaignLevelDataId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<bool>("Beaten")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Index")
                        .HasColumnType("integer");

                    b.Property<double>("PersonalHighscore")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserSaveDataId")
                        .HasColumnType("text");

                    b.Property<int>("World")
                        .HasColumnType("integer");

                    b.HasKey("UserCampaignLevelDataId");

                    b.HasIndex("UserSaveDataId");

                    b.ToTable("UserCampaignLevelData");
                });

            modelBuilder.Entity("SFServer.Models.DB.UserSaveData", b =>
                {
                    b.Property<string>("UserSaveDataId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("DebraUnlocked")
                        .HasColumnType("boolean");

                    b.Property<bool>("HonkyUnlocked")
                        .HasColumnType("boolean");

                    b.Property<bool>("JawsUnlocked")
                        .HasColumnType("boolean");

                    b.Property<bool>("KokoUnlocked")
                        .HasColumnType("boolean");

                    b.Property<bool>("LeonUnlocked")
                        .HasColumnType("boolean");

                    b.Property<bool>("NuggetUnlocked")
                        .HasColumnType("boolean");

                    b.Property<bool>("OlipherUnlocked")
                        .HasColumnType("boolean");

                    b.Property<bool>("PatchyUnlocked")
                        .HasColumnType("boolean");

                    b.Property<bool>("PepeUnlocked")
                        .HasColumnType("boolean");

                    b.Property<bool>("PerryUnlocked")
                        .HasColumnType("boolean");

                    b.Property<bool>("PingoUnlocked")
                        .HasColumnType("boolean");

                    b.Property<bool>("RexUnlocked")
                        .HasColumnType("boolean");

                    b.Property<bool>("SpeedyUnlocked")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("UserSaveDataId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserSaveData");
                });

            modelBuilder.Entity("SFServer.Models.DailyChallenge.DailyChallenge", b =>
                {
                    b.Property<string>("DailyChallengeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("DiscordMessageId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("LevelId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("DailyChallengeId");

                    b.ToTable("DailyChallenges");
                });

            modelBuilder.Entity("SFServer.Models.DailyChallenge.DailyChallengeParticipant", b =>
                {
                    b.Property<string>("DailyChallengeParticipantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DailyChallengeId")
                        .HasColumnType("text");

                    b.Property<string>("Nickname")
                        .HasColumnType("text");

                    b.Property<double>("Time")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("DailyChallengeParticipantId");

                    b.ToTable("DailyChallengeParticipants");
                });

            modelBuilder.Entity("SFServer.Models.Notifications.Notification", b =>
                {
                    b.Property<string>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("Body")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeeplinkUrl")
                        .HasColumnType("text");

                    b.Property<int>("NotificationType")
                        .HasColumnType("integer");

                    b.Property<bool>("Read")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("NotificationId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("SFServer.Models.Notifications.NotificationLink", b =>
                {
                    b.Property<string>("NotificationLinkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("ButtonText")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NotificationId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasKey("NotificationLinkId");

                    b.HasIndex("NotificationId");

                    b.ToTable("NotificationLinks");
                });

            modelBuilder.Entity("SFServer.Security.Token", b =>
                {
                    b.Property<string>("TokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("ClientId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenString")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("TokenId");

                    b.HasIndex("UserId");

                    b.ToTable("Tokens");
                });

            modelBuilder.Entity("SFServer.Models.DB.Following", b =>
                {
                    b.HasOne("SFServer.Models.DB.User", "Follower")
                        .WithMany("Following")
                        .HasForeignKey("UserFollowingId");
                });

            modelBuilder.Entity("SFServer.Models.DB.Level", b =>
                {
                    b.HasOne("SFServer.Models.DB.User", null)
                        .WithMany("Levels")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("SFServer.Models.DB.UserCampaignLevelData", b =>
                {
                    b.HasOne("SFServer.Models.DB.UserSaveData", null)
                        .WithMany("CampaignLevelData")
                        .HasForeignKey("UserSaveDataId");
                });

            modelBuilder.Entity("SFServer.Models.DB.UserSaveData", b =>
                {
                    b.HasOne("SFServer.Models.DB.User", null)
                        .WithOne("SaveData")
                        .HasForeignKey("SFServer.Models.DB.UserSaveData", "UserId");
                });

            modelBuilder.Entity("SFServer.Models.Notifications.NotificationLink", b =>
                {
                    b.HasOne("SFServer.Models.Notifications.Notification", null)
                        .WithMany("Links")
                        .HasForeignKey("NotificationId");
                });

            modelBuilder.Entity("SFServer.Security.Token", b =>
                {
                    b.HasOne("SFServer.Models.DB.User", null)
                        .WithMany("Tokens")
                        .HasForeignKey("UserId");
                });
#pragma warning restore 612, 618
        }
    }
}
